name: "Deploy to GitHub Pages"

on: workflow_dispatch

jobs:
    buildAndDeploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: "npm install --production"
            - run: "npm run deploy"
