name: "Deploy to GitHub Pages"

on: workflow_dispatch

jobs:
    buildAndDeploy:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - run: "npm ci"
            - run: "npm run deploy"
